name: Setup SSH Port Forwarding with Ngrok

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ngrok
        run: |
          curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/ngrok
          rm ngrok-stable-linux-amd64.zip

      - name: Update Ngrok
        run: |
          ngrok update

      - name: Start Ngrok SSH
        run: |
          ngrok authtoken 2eYRlI6wC9kvgtop6dllNaZimM9_81BKjfQ7YHnfvvs89kFVJ
          ngrok tcp 22
