name: Setup and Connect Termius Tunnel
on: [push, pull_request]

jobs:
  setup_tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Termius
        run: |
          curl -fsSL https://get.termius.com/linux | sudo bash

      - name: Setup SSH server (replace with actual setup commands)
        run: |
          # Replace these commands with actual setup commands for SSH server
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh
          sudo systemctl enable ssh
          # Configure SSH server as needed

      - name: Create SSH tunnel with Termius
        run: |
          termius login vghogare34@outlook.com Vaibhav@123&
          termius ssh create --local-port=12345 --remote-port=22 
