name: Enable SSH and Get IP

on:
  push:
    branches:
      - main

jobs:
  ssh-and-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Enable SSH
        run: sudo service ssh start

      - name: Get IP Address
        id: get_ip
        run: echo "::set-output name=ip_address::$(curl -s https://api.ipify.org)"

      - name: Get Username
        id: get_username
        run: echo "::set-output name=username::$(whoami)"

      - name: Print IP Address and Username
        run: |
          echo "IP Address: ${{ steps.get_ip.outputs.ip_address }}"
          echo "Username: ${{ steps.get_username.outputs.username }}"
